
<meta charset="utf-8">
<html lang="ko">
<head>
    <link rel="stylesheet" type="text/css" href="./../style.css" />
    <title>[JAVA] 예외 처리 Catch Exception</title>
</head>
<body id="tt-body-page" class="">
<div id="wrap" class="wrap-right">
    <div id="container">
        <main class="main ">
            <div class="area-main">
                <div class="area-view">
                    <div class="article-header">
                        <div class="inner-article-header">
                            <div class="box-meta">
                                <h2 class="title-article">[JAVA] 예외 처리 Catch Exception</h2>
                                <div class="box-info">
                                    <p class="category">Back-end/Java Fundamental</p>
                                    <p class="date">2024-07-04 14:54:31</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="article-view">
                        <div class="contents_style">
                            <p style="text-align: center;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">"Exception 예외" 란, 프로그램이 예기치 못한 상황으로 인해 발생하는 현상으로 배열의 범위에서 벗어 났을때 발생하는 IndexOutOfBoundsException, 런타임에 발생하는 RuntimeError 등 다양한 예외 상황이 존재한다.&nbsp;</span></p>
<p style="text-align: center;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">Java 언어는 이러한 다양한 예외를 처리하기 위한 문법을 제공한다.&nbsp;</span></p>
<p style="text-align: center;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">예외를 처리하기 위해서는 두 가지 규칙만 생각하면 된다. <b>"1. 예외를 잡거나" "2. 예외를 외부로 던지거나"&nbsp;</b></span><span style="font-family: 'Nanum Gothic'; color: #000000;"></span></p>
<p style="text-align: center;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">이번 포스팅 에서는 <b>예외를 잡는 방법</b>에 대해서 정리해 보고자 한다.</span></p>
<p style="text-align: center;" data-ke-size="size16">&nbsp;</p>
<p style="text-align: center;" data-ke-size="size18"><span style="font-family: 'Nanum Gothic'; color: #000000;"><b>#1 예외 계층</b></span></p>
<p style="text-align: center;" data-ke-size="size18"><span style="font-family: 'Nanum Gothic'; color: #000000;"><b>#2 Catch Exception</b></span></p>
<p style="text-align: center;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">#2.1 try ~ catch</span></p>
<p style="text-align: center;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">#2.2 try ~ catch ~fianlly&nbsp;</span></p>
<p style="text-align: center;" data-ke-size="size18"><b><span style="font-family: 'Nanum Gothic'; color: #000000;">#3 사용자 정의 예외</span></b></p>
<p style="text-align: center;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">#3.1 커스텀 체크 예외</span></p>
<p style="text-align: center;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">#3.2 커스텀 언체크 예외&nbsp;</span></p>
<p style="text-align: center;" data-ke-size="size16">&nbsp;</p>
<p style="text-align: center;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000; background-color: #c0d1e7;">*개인적인 공부 내용을 기록하는 용도로 작성한 글 이기에 <b>잘못된 내용</b>을 포함하고 있을 수 있습니다.</span></p>
<hr contenteditable="false" data-ke-type="horizontalRule" data-ke-style="style5" />
<h2 data-ke-size="size26"><span style="font-family: 'Nanum Gothic'; color: #dddddd; background-color: #333333;">#1 예외 계층</span></h2>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">예외 또한 객체이다. 즉, 결국 하나의 클래스와 다를게 없다는 것이다. </span></p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">예외는 모든 객체의 부모 객체인 Object 객체를 상속받은 <span style="background-color: #333333; color: #dddddd;">Throwable 객체</span>에서 관리된다.</span></p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">또한 <span style="background-color: #c0d1e7;">어떠한 객체를 상속 받는 지</span>에 따라서 다음과 같이 구분한다.&nbsp;</span></p>
<p data-ke-size="size16">&nbsp;</p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;"><span style="background-color: #333333; color: #dddddd;">체크 예외 Checked Exception</span> : Exception 객체를 상속받는 예외로 주로 컴파일 타임에서 발생하는 예외들을 관리한다. <span style="background-color: #c0d1e7;">체크 예외는 프로그래머가 반드시 오류를 잡아서 처리해 주어야 한다. </span></span></p>
<p data-ke-size="size16">&nbsp;</p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;"><span style="background-color: #333333; color: #dddddd;">언체크 예외 UnChecked Exception</span> : Runtime Exception 객체를 상속받는 예외로 주로 런타임에 발생하는 예외들을 관리한다. <span style="background-color: #c0d1e7;">언체크 예외는 프로그래가 별도로 오류를 잡아주지 않아도 된다.&nbsp;</span></span></p>
<p data-ke-size="size16">&nbsp;</p>
<p><figure class="imageblock alignLeft" width="680" height="469" >
    <span data-lightbox="lightbox">
        <img src="./img/img.png" width="680" height="469"  />
    </span>
    <figcaption></figcaption>
</figure></p>
<hr contenteditable="false" data-ke-type="horizontalRule" data-ke-style="style5" />
<h2 data-ke-size="size26"><span style="font-family: 'Nanum Gothic'; color: #000000;"><span style="background-color: #333333; color: #dddddd;">#2 Catch Exception</span>&nbsp;</span></h2>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">먼저 오류를 잡는 방법에 대해서 정리해 보고자 한다.&nbsp;</span></p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">간단한 예제를 통해 예외가 발생하는 상황을 처리하는 방법에 대해서 알아보자. 다음 코드는 <span style="background-color: #c0d1e7;">크기가 5인 배열 array에 6번째 인덱스에 접근을 시도</span>하기에, 배열의 범위를 벗어 났다는 <span style="background-color: #333333; color: #dddddd;">IndexOutOfBoundsException</span> 에러가 발생한다.&nbsp;</span></p>
<pre id="code_1719895331610" class="java" data-ke-language="java" data-ke-type="codeblock"><code>public class ErrorMain {
    static int array[] = {1, 2, 3, 4, 5};
    public static void main(String[] args) {
        int access = array[6]; // IndexOutOfBoundsException Error
    }
}</code></pre>
<pre id="code_1719898419867" class="java" data-ke-language="java" data-ke-type="codeblock"><code>Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 5
	at exception.ErrorMain.main(ErrorMain.java:6)</code></pre>
<p data-ke-size="size16">&nbsp;</p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">이처럼 오류를 잡아주지 않으면 오류가 메인 함수 밖으로 나가 프로그램이 종료 되어 버리고 만다.&nbsp;</span></p>
<p data-ke-size="size16">&nbsp;</p>
<h3 data-ke-size="size23"><span style="font-family: 'Nanum Gothic'; color: #dddddd; background-color: #333333;">#2.1 try ~ catch</span></h3>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">자바에서 제공하는 <span style="background-color: #333333; color: #dddddd;">try ~ catch</span> 문을 사용하면 발생하는 오류를 잡을 수 있다.&nbsp;</span></p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;"><span style="background-color: #c0d1e7;">try 블럭 내부에는 코드가 실행되는 정상 로직</span>을 <span style="background-color: #c0d1e7;">catch 블럭 내부에는 예외 흐름</span>을 기입한다.&nbsp;</span></p>
<pre id="code_1719898044480" class="java" data-ke-language="java" data-ke-type="codeblock"><code>public class ErrorMain {
    static int array[] = {1, 2, 3, 4, 5};
    public static void main(String[] args) {
        try {
            int access = array[6];
        } catch (IndexOutOfBoundsException e) {
            System.out.println(e.getMessage());
        }
    }
}</code></pre>
<pre id="code_1719898270165" class="java" data-ke-language="java" data-ke-type="codeblock"><code>Index 6 out of bounds for length 5</code></pre>
<p data-ke-size="size16">&nbsp;</p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">⭐️ <b>예외&nbsp;객체 e</b></span></p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">객체 e 는 오류에 관한 정보를 포함하고 있다. 자주 사용되는 메서드는 다음과 같다.&nbsp;</span></p>
<table style="border-collapse: collapse; width: 100%;" border="1" data-ke-align="alignLeft">
<tbody>
<tr>
<td style="width: 17.3256%;"><b><span style="font-family: 'Nanum Gothic'; color: #000000; text-align: start;">e.getMessage()<span>&nbsp;</span></span></b></td>
<td style="width: 82.6744%;"><span style="font-family: 'Nanum Gothic'; color: #000000; text-align: start;">오류가 발생한 원인 메시지를 출력한다.</span></td>
</tr>
<tr>
<td style="width: 17.3256%;"><b><span style="font-family: 'Nanum Gothic'; color: #000000; text-align: start;">e.printStackTrace()</span></b></td>
<td style="width: 82.6744%;"><span style="font-family: 'Nanum Gothic'; color: #000000; text-align: start;">오류가 발생한 스택 트레이스를 출력한다. 주로 디버깅 시 유용하게 활용된다.</span></td>
</tr>
<tr>
<td style="width: 17.3256%;"><b><span style="font-family: 'Nanum Gothic'; color: #000000; text-align: start;">e.toString()</span></b></td>
<td style="width: 82.6744%;"><span style="font-family: 'Nanum Gothic'; color: #000000; text-align: start;">오류에 대한 설명과 클래스를 문자열 형태로 반환한다.&nbsp;</span></td>
</tr>
</tbody>
</table>
<p data-ke-size="size16">&nbsp;</p>
<h3 data-ke-size="size23"><span style="font-family: 'Nanum Gothic'; color: #000000;"><span style="background-color: #333333; color: #dddddd;">#2.2 try ~ catch ~ finally</span>&nbsp;</span></h3>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">try ~ catch 문법은 try 로직 흐름에서 예외가 발생하면 발생한 코드 흐름에서 바로 catch 문법으로 넘어가 오류를 잡은 뒤 블록에서 벗어나 버린다.&nbsp;</span></p>
<pre id="code_1719899367463" class="java" data-ke-language="java" data-ke-type="codeblock"><code>public class ErrorMain {
    static int array[] = {1, 2, 3, 4, 5};
    public static void main(String[] args) {
        try {
            int access = array[6];
            System.out.println("array[1] = " + array[1]); // 해당 로직은 실행되지 않음.
        } catch (IndexOutOfBoundsException e) {
            System.out.println(e.getMessage());
        }
    }
}</code></pre>
<p data-ke-size="size16">&nbsp;</p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">만약 예외 상황에 관계 없이 반드시 실행 되어야 하는 로직 (서버 자원을 해제하는 등..) 이 존재한다면 finally 부분에 실행을 보장한 코드를 작성해 주면 된다.&nbsp;</span></p>
<pre id="code_1719899518805" class="java" data-ke-language="java" data-ke-type="codeblock"><code>public class ErrorMain {
    static int array[] = {1, 2, 3, 4, 5};
    public static void main(String[] args) {
        try {
            int access = array[6];
        } catch (IndexOutOfBoundsException e) {
            System.out.println(e.getMessage());
        } finally {
            System.out.println("array[1] = " + array[1]); // 해당 로직은 항상 실행을 보장
        }
    }
}</code></pre>
<pre id="code_1719899534806" class="java" data-ke-language="java" data-ke-type="codeblock"><code>Index 6 out of bounds for length 5
array[1] = 2</code></pre>
<hr contenteditable="false" data-ke-type="horizontalRule" data-ke-style="style5" />
<h2 style="color: #000000; text-align: start;" data-ke-size="size26"><span style="font-family: 'Nanum Gothic'; color: #dddddd; background-color: #333333;">#3 사용자 정의 예외</span></h2>
<p style="color: #333333; text-align: start;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">예외의 상속 구조를 잘 숙지하면 커스텀 예외를 만드는 것은 어렵지 않다.&nbsp;</span></p>
<p style="color: #333333; text-align: start;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">예외 또한 클래스로 관리되기에 SQLexception이 발생하면 Exception 부모 객체를 상속받은&nbsp;SQLexception 클래스가 초기화되고,</span></p>
<p style="color: #333333; text-align: start;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">NullPointerCheck 예외가 발생하면 Runtime exception 예외를 상속받은&nbsp;<span style="text-align: start;">NullPointerCheck&nbsp;클래스가 초기화 되는 것 뿐이다.</span></span></p>
<p style="color: #333333; text-align: start;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;"><span style="text-align: start;">예외는 throw 문법을 사용하여 발생시키며,<span style="color: #666666;"><i> 예외를 던지는 방법에 대해서는 다른 포스팅에 별도로 작성할 예정이다. </i></span></span></span></p>
<p style="color: #333333; text-align: start;" data-ke-size="size16">&nbsp;</p>
<h3 style="color: #333333; text-align: start;" data-ke-size="size23"><span style="font-family: 'Nanum Gothic'; color: #000000;"><span style="background-color: #333333; color: #dddddd;">#3.1 커스텀 체크 예외 예제&nbsp;</span>&nbsp;</span></h3>
<p style="color: #333333; text-align: start;" data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000;">다음 코드는 Exception 클래스를 상속받은 MyChekcedException 체크 예외를 생성한 뒤, 메인 함수에서 실행한 예제이다. </span></p>
<pre id="code_1720071751175" class="java" data-ke-language="java" data-ke-type="codeblock"><code>public class MyCheckedException extends Exception {
    // 부모 클래스 Exception 의 생성자를 호출하여, 에러 메시지 저장
    public MyCheckedException(String message) {
        super(message);
    }
}</code></pre>
<pre id="code_1720071814486" class="java" data-ke-language="java" data-ke-type="codeblock"><code>public class ErrorMain {
    public static void main(String[] args) {
        try {
            throw new MyCheckedException("checked Exception"); // 에러 발생
        } catch (Exception e) {
            System.out.println("error message - " + e.getMessage());
        }
    }
}</code></pre>
<pre id="code_1720071828548" class="java" data-ke-language="java" data-ke-type="codeblock"><code>[output]
error message - checked Exception</code></pre>
<p data-ke-size="size16">&nbsp;</p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000; text-align: start;">체크 예외는 프로그래머가 반드시 예외를 잡아 주어야 하기에, try 블록 내부에 예외 발생 코드를 작성해 주지 않으면, 컴파일이 되지 않는다.</span></p>
<pre id="code_1720072156715" class="java" data-ke-language="java" data-ke-type="codeblock"><code>public class ErrorMain {
    public static void main(String[] args) {
        throw new MyCheckedException("checked Exception"); // 컴파일 에러
    }
}</code></pre>
<pre id="code_1720072186821" class="java" data-ke-language="java" data-ke-type="codeblock"><code>java: unreported exception exception.basic.checked.MyCheckedException; must be caught or declared to be thrown</code></pre>
<h3 data-ke-size="size23"><br /><span style="font-family: 'Nanum Gothic'; color: #000000; text-align: start;"><span style="background-color: #333333; color: #dddddd;">#3.2 커스텀 언체크 예외 예제</span>&nbsp;&nbsp;</span><span style="font-family: 'Nanum Gothic'; color: #000000; text-align: start;"></span></h3>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic'; color: #000000; text-align: start;">언체크 예외 또한 앞 코드에서 부모 예외 클래스가 Exception에서 RuntimeException으로 바뀌었다는 것 빼고는 동일하다.</span></p>
<pre id="code_1720071935333" class="java" data-ke-language="java" data-ke-type="codeblock"><code>/**
 * RuntimeException을 상속받은 예외는 언체크 예외가 된다.
 */
public class MyUncheckedException extends RuntimeException{
    public MyUncheckedException(String message) {
        super(message);
    }
}</code></pre>
<pre id="code_1720071974118" class="java" data-ke-language="java" data-ke-type="codeblock"><code>public class ErrorMain {
    public static void main(String[] args) {
        try {
            throw new MyUncheckedException("UnChecked Exception"); // 에러 발생
        } catch (Exception e) {
            System.out.println("error message - " + e.getMessage());
        }
    }
}</code></pre>
<pre id="code_1720072041395" class="java" data-ke-language="java" data-ke-type="codeblock"><code>error message - UnChecked Exception</code></pre>
<p data-ke-size="size16">&nbsp;</p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic';">언체크 예외는 프로그래머가 별도로 try ~ catch 문법으로 예외를 잡아 주지 않아도 정상적으로 컴파일 된다.&nbsp;</span></p>
<p data-ke-size="size16"><span style="font-family: 'Nanum Gothic';">하지만 이 경우 예외가 main 함수 밖으로 나가게 되어 프로그램이 종료된다.&nbsp;</span></p>
<pre id="code_1720072302168" class="java" data-ke-language="java" data-ke-type="codeblock"><code>public class ErrorMain {
    public static void main(String[] args) {
        /**
         * 에러를 잡아주지 않아도 컴파일러에서 오류를 발생 시키지 않음.
         */
        throw new MyUncheckedException("UnChecked Exception");
    }
}</code></pre>
<pre id="code_1720072311041" class="java" data-ke-language="java" data-ke-type="codeblock"><code>Exception in thread "main" exception.basic.unchecked.MyUncheckedException: UnChecked Exception
	at exception.basic.unchecked.ErrorMain.main(ErrorMain.java:10)</code></pre>
                        </div>
                        <br/>
                        <div class="tags">
                            
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
</body>
</html>
